// Code generated by scaf. DO NOT EDIT.
//go:build !scaf_prod

package main

func init() {
	getUserImpl = getUserMock
	countUsersImpl = countUsersMock
}

func getUserMock(userId any) (any, any, any) {
	if userId == 1 {
		return "Alice", "alice@example.com", 30
	} else if userId == 2 {
		return "Bob", nil, 25
	} else if userId == 999 {
		return nil, nil, nil
	} else if userId == 1 {
		return "Bruh", nil, nil
	} else if userId == 1 {
		return nil, nil, "thirty"
	}
	panic("no matching test case")
}

func countUsersMock() any {
	if true {
		return 2
	} else if true {
		return 3
	} else if true {
		return 2
	}
	panic("no matching test case")
}
