// Code generated by scaf. DO NOT EDIT.

package main

import (
	"context"
	"github.com/rlch/neogo"
)

func GetUser(ctx context.Context, db neogo.Driver, userId any) (any, any, any, any, error) {
	return getUserImpl(ctx, db, userId)
}

var getUserImpl func(context.Context, neogo.Driver, any) (any, any, any, any, error) = getUserProd

func getUserProd(ctx context.Context, db neogo.Driver, userId any) (any, any, any, any, error) {
	var name any
	var email any
	var age any
	var verified any
	err := db.Exec().
		Cypher(`MATCH (u:User {id: $userId})
	RETURN u.name, u.email, u.age, u.verified`).
		RunWithParams(ctx, map[string]any{"userId": userId}, "u.name", &name, "u.email", &email, "u.age", &age, "u.verified", &verified)
	if err != nil {
		return nil, nil, nil, nil, err
	}
	return name, email, age, verified, nil
}

func CountUsers(ctx context.Context, db neogo.Driver) (any, error) {
	return countUsersImpl(ctx, db)
}

var countUsersImpl func(context.Context, neogo.Driver) (any, error) = countUsersProd

func countUsersProd(ctx context.Context, db neogo.Driver) (any, error) {
	var cnt any
	err := db.Exec().
		Cypher(`MATCH (u:User)
	RETURN count(u) as cnt`).
		Run(ctx, "cnt", &cnt)
	if err != nil {
		return nil, err
	}
	return cnt, nil
}

func CreatePost(ctx context.Context, db neogo.Driver, title any, authorId any) (any, any, error) {
	return createPostImpl(ctx, db, title, authorId)
}

var createPostImpl func(context.Context, neogo.Driver, any, any) (any, any, error) = createPostProd

func createPostProd(ctx context.Context, db neogo.Driver, title any, authorId any) (any, any, error) {
	var title any
	var authorId any
	err := db.Exec().
		Cypher(`CREATE (p:Post {title: $title, authorId: $authorId})
	RETURN p.title, p.authorId`).
		RunWithParams(ctx, map[string]any{"title": title, "authorId": authorId}, "p.title", &title, "p.authorId", &authorId)
	if err != nil {
		return nil, nil, err
	}
	return title, authorId, nil
}
