# yaml-language-server: $schema=https://raw.githubusercontent.com/rlch/scaf/refs/heads/master/.scaf.schema.json

neo4j:
  uri: bolt://localhost:7687

generate:
  adapter: neogo
  schema: .scaf-schema.yaml
  package: movies
