// Code generated by scaf. DO NOT EDIT.
//go:build !scaf_prod

package movies

import (
	"context"
	"github.com/rlch/neogo"
)

func init() {
	findActorsImpl = findActorsMock
	findDirectorsImpl = findDirectorsMock
	findReviewsImpl = findReviewsMock
}

func findActorsMock(ctx context.Context, db neogo.Driver, name string) ([]*findActorsResult, error) {
	if name == "Tom Hanks" {
		return []*findActorsResult{{
			Name: "Tom Hanks",
			Title: "Forrest Gump",
			Roles: nil,
		}}, nil
	}
	panic("no matching test case")
}

func findDirectorsMock(ctx context.Context, db neogo.Driver) ([]*findDirectorsResult, error) {
	if true {
		return []*findDirectorsResult{{
			Name: "Robert Zemeckis",
			Title: "Forrest Gump",
		}}, nil
	}
	panic("no matching test case")
}

func findReviewsMock(ctx context.Context, db neogo.Driver, title string) ([]*findReviewsResult, error) {
	if title == "The Matrix" {
		return []*findReviewsResult{{
			Name: "",
			Summary: "",
			Rating: 5,
		}}, nil
	}
	panic("no matching test case")
}
