// Code generated by scaf. DO NOT EDIT.

package shared

import (
	"context"
	"github.com/rlch/neogo"
)

func SetupUsers(ctx context.Context, db neogo.Driver) error {
	return setupUsersImpl(ctx, db)
}

var setupUsersImpl func(context.Context, neogo.Driver) error = setupUsersProd

func setupUsersProd(ctx context.Context, db neogo.Driver) error {
	err := db.Exec().
		Cypher(`CREATE (alice:User {id: 1, name: "Alice", email: "alice@example.com", age: 30, verified: true})
	CREATE (bob:User {id: 2, name: "Bob", email: "bob@example.com", age: 25, verified: false})
	CREATE (charlie:User {id: 3, name: "Charlie", email: "charlie@example.com", age: null, verified: true})`).
		Run(ctx)
	if err != nil {
		return err
	}
	return nil
}

func SetupPosts(ctx context.Context, db neogo.Driver, postId any, title any, authorId any) error {
	return setupPostsImpl(ctx, db, postId, title, authorId)
}

var setupPostsImpl func(context.Context, neogo.Driver, any, any, any) error = setupPostsProd

func setupPostsProd(ctx context.Context, db neogo.Driver, postId any, title any, authorId any) error {
	err := db.Exec().
		Cypher(`CREATE (p:Post {id: $postId, title: $title, authorId: $authorId, views: 0})`).
		RunWithParams(ctx, map[string]any{"postId": postId, "title": title, "authorId": authorId})
	if err != nil {
		return err
	}
	return nil
}

func SetupCleanDB(ctx context.Context, db neogo.Driver) error {
	return setupCleanDBImpl(ctx, db)
}

var setupCleanDBImpl func(context.Context, neogo.Driver) error = setupCleanDBProd

func setupCleanDBProd(ctx context.Context, db neogo.Driver) error {
	err := db.Exec().
		Cypher(`MATCH (n) DETACH DELETE n`).
		Run(ctx)
	if err != nil {
		return err
	}
	return nil
}
